#!/bin/sh

dbdir=/var/lib/dpkg

# Backup the 7 last versions of dpkg databases containing user data.
if cd /var/backups ; then
    # We backup all relevant database files if any has changed, so that
    # the rotation number always contains an internally consistent set.
    dbchanged=no
    dbfiles="arch status diversions statoverride"
    for db in $dbfiles ; do
        if ! cmp -s "dpkg.${db}.0" "$dbdir/$db"; then
            dbchanged=yes
            break;
        fi
    done
    if [ "$dbchanged" = "yes" ] ; then
        for db in $dbfiles ; do
            [ -e "$dbdir/$db" ] || continue
            cp -p "$dbdir/$db" "dpkg.$db"
            savelog -c 7 "dpkg.$db" >/dev/null
        done
    fi

    # The alternatives database is independent from the dpkg database.
    dbalt=alternatives

    # XXX: Ideally we'd use --warning=none instead of discarding stderr, but
    # as of GNU tar 1.27.1, it does not seem to work reliably (see #749307).
    if ! test -e ${dbalt}.tar.0 ||
       ! tar -df ${dbalt}.tar.0 -C $dbdir $dbalt >/dev/null 2>&1 ;
    then
        tar -cf ${dbalt}.tar -C $dbdir $dbalt >/dev/null 2>&1
        savelog -c 7 ${dbalt}.tar >/dev/null
    fi
fi
