#!/bin/sh

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Recreate the /usr/local/share/ca-certificates directory, since we are
        # ignoring Debian Policy by intentionally installing here. Removal of
        # ca-certificates-local removes this directory if empty.
        if [ ! -e /usr/local/share/ca-certificates ]; then
            if mkdir /usr/local/share/ca-certificates 2>/dev/null; then
                chown root:staff /usr/local/share/ca-certificates
                chmod 2775 /usr/local/share/ca-certificates
            fi
        fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
