#!/bin/sh
# See deb-postrm(5).

set -e

# Remove log file when dpkg is purged
remove_logfile() {
    logdir=$DPKG_ROOT/var/log

    rm -f "$logdir"/dpkg.log "$logdir"/dpkg.log.* 2>/dev/null
    rm -f "$logdir"/alternatives.log "$logdir"/alternatives.log.* 2>/dev/null
}

case "$1" in
    remove)
	;;

    purge)
	remove_logfile
	;;

    upgrade)
	;;

    failed-upgrade|disappear|abort-install|abort-upgrade)
	;;


    *)
	echo "$0 called with unknown argument '$1'" 1>&2
	exit 1
	;;
esac


exit 0
