#!/bin/sh
set -e
# Automatically added by dh_installdeb/12.1.1
dpkg-maintscript-helper rm_conffile /etc/apt/apt.conf.d/20changelog 1.2.4\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/cron.daily/apt 1.2.10\~ -- "$@"
# End automatically added section
# Automatically added by dh_systemd_start/12.1.1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'apt-daily-upgrade.timer' 'apt-daily.timer' >/dev/null || true
fi
# End automatically added section
